language: php
php:
  - 5.4
  - 5.5
  - 5.6
#  - hhvm
#  - hhvm-nightly

services:
  - mysql

before_install:
  - pear channel-discover pear.phing.info
  - pear install phing/phing
  - phpenv rehash

install:
  - cd .. && git clone https://github.com/yiisoft/yii.git yii
  - cd yii && git checkout 2e702fa83a64b6417addebf485ab6af9dabc1dfe
  - cd ../argilla
#  - wget https://phar.phpunit.de/phpunit-3.7.38.phar
#  - chmod +x phpunit-3.7.38.phar
#  - sudo mv phpunit-3.7.38.phar phpunit.phar

before_script:
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'prog'@'localhost' IDENTIFIED BY '123' WITH GRANT OPTION;" -uroot
  - phing bootstrap -DdbName=argilla -DdbTablePrefix=argilla_ -DdbUser=prog -DdbPassword=123 -Dconfirm=y -DconfirmTest=y
#  - phing applySchema -Dconfirm=y -DconfirmTest=y
#  - php protected/yiic.php migrate --interactive=0

script:
  - phpunit -c backend/protected/tests/phpunit.xml backend/protected/tests/unit/
  - phpunit -c protected/tests/phpunit.xml protected/tests/unit/